<?php
/**
 * Created by PhpStorm.
 * User: jinxiu89
 * Date: 2019/7/20
 * Time: 16:39
 */
namespace app\en_us\controller;


use app\common\helper\Category;
use app\common\model\Service\ServiceCategory;
use app\wavlink\service\service\driversCategory as service;
use think\App;
use app\common\model\Service\Firmware as model;
use app\en_us\validate\Firmware as validate;
use think\db\exception\DataNotFoundException;
use think\db\exception\ModelNotFoundException;
use think\Exception;
use think\exception\DbException;

/**
 * Class Firmware
 * @package app\en_us\controller
 */
class Firmware extends Base
{
    protected $model;
    protected $validate;

    public function __construct(App $app = null)
    {
        parent::__construct($app);
        $this->model = new model();
        $this->validate = new validate();
        //todo:: 这里在真个无极分类做好后会进入一个休整，将一些分类的东西聚合起来 再传递到前端
        try {
            $cate = ServiceCategory::getTree($this->code,'Firmware');
            $this->assign('fw', $cate);
        } catch (DataNotFoundException $e) {
        } catch (ModelNotFoundException $e) {
        } catch (DbException $e) {
        }
        $data = (new service())->getDataByLanguageId($status = 1, $this->language_id);
        $level = Category::toLevel($data['data']->toArray()['data'], '&emsp;&emsp;');
        $this->assign('cate', $level);
    }
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

    }

    /***
     * @param string $order
     * @return mixed
     */
    public function index($order = 'desc')
    {
        try {
            $parent = [
                'seo_title' => lang('firmware'),
                'keywords' => lang('firmware'),
                'description' => lang('firmware'),
            ];
            $result = $this->model->getDataByLanguageId($this->language_id, 1, $order);
            return $this->fetch($this->template . '/firmware/index.html', [
                'data' => $result['data'],
                'count' => $result['count'],
                'parent' => $parent,
                'order' => $order
            ]);
        } catch (Exception $exception) {
            //todo::错误的页面渲染
            $this->error($exception->getMessage());
        }
    }

    /**
     * @param $title
     * @return mixed
     */
    public function details($title)
    {
        try {
            $result = $this->model->getDataByTitle($title);
            return $this->fetch($this->template . '/firmware/details.html', [
                'result' => $result
            ]);
        } catch (Exception $exception) {
            $this->error($exception->getMessage());
        }
    }
}