<?php
/**
 * @Create by PhpStorm
 * @author:jinxiu89@163.com
 * @Create Date:2020/12/23 15:53
 * @User: kevin
 * @Current File : Email.php
 * @格言：溪涧岂能留得住，终归大海做波涛 --李忱
 * @格言： 我的内心因看见大海而波涛汹涌
 **/

namespace app\wavlink\controller\Marketing;


use app\wavlink\controller\BaseAdmin;
use think\App;

/**
 * Class Email
 * @package app\wavlink\controller\Marketing
 */
class Email extends BaseAdmin
{
    public function __construct(App $app = null)
    {
        parent::__construct($app);
    }

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    /**
     * @return string
     */
    public function index(): string
    {
        return "hello email";
    }
}